python project
readme for 4th 
pyhton exception
